version: '3'
services:
  realman:
    build: .
    env_file:
      - .env
    ports:
      - '8008:8000'
    depends_on:
      - redis
      - mysql
    image: fastapi-t
    command: uvicorn fatapi_t.main:app --port 8000 --host 0.0.0.0
  timing-worker:
    env_file:
      - .env
    image: realman
    depends_on:
      - realman
    command: rearq worker realman.factory:rearq --timer
  task-worker:
    env_file:
      - .env
    image: realman
    depends_on:
      - realman
    command: rearq worker realman.factory:rearq -q task
  redis:
    hostname: redis
    image: redis
    volumes:
      - ./redis/data:/data
  mysql:
    hostname: mysql
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password #这行代码解决无法访问的问题
    volumes:
      - /mysql/data:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE:fastapi-t
      - LANG=C.UTF-8mb4