version: '3'
services:
  realman:
    build: .
    env_file:
      - .env
    ports:
      - '8008:8000'
    depends_on:
      - redis
    image: realman
    command: uvicorn realman.main:app --port 8000 --host 0.0.0.0
  timing-worker:
    env_file:
      - .env
    image: realman
    depends_on:
      - realman
    command: rearq worker realman.factory:rearq --timer
  task-worker:
    env_file:
      - .env
    image: realman
    depends_on:
      - realman
    command: rearq worker realman.factory:rearq -q task
  withdraw-worker:
    env_file:
      - .env
    image: realman
    depends_on:
      - realman
    command: rearq worker realman.factory:rearq -q withdraw
  notify-worker:
    env_file:
      - .env
    image: realman
    depends_on:
      - realman
    command: rearq worker realman.factory:rearq -q notify
  pass-task-worker:
    env_file:
      - .env
    image: realman
    depends_on:
      - realman
    command: rearq worker realman.factory:rearq -q pass_task
  redis:
    hostname: redis
    image: redis
    volumes:
      - ./redis/data:/data
